version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: education_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - education_network

  mongodb:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: education_analytics
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - education_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - education_network

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
      - MONGODB_HOST=mongodb
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - mongodb
      - redis
    volumes:
      - .:/app
    networks:
      - education_network

volumes:
  postgres_data:
  mongodb_data:

networks:
  education_network:
    driver: bridge
